## Numpy : Practice Problem

1.Extract all odd numbers from an array

In [4]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[arr%2==1])

[1 3 5 7 9]


2.Replace all odd numbers in arr with -1

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==1]=-1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


3.Convert a 1D array to a 2D array with 2 rows

In [6]:
arr=np.arange(10)
arr = np.reshape(arr,(2,5))
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


4.Stack arrays a and b vertically

In [7]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c=np.vstack((a,b))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


5.Get all items between 5 and 10 from a

In [8]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a = a[(a>=5)*(a<=10)]
print(a)

[ 6  9 10]


6.Create a null vector of size 10 but the fifth value which is 1.


In [9]:
z = np.zeros(10,int)
z[4]=1
z

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

7.Create a vector with values ranging from 10 to 49.

In [10]:
vec = np.arange(10,50)
vec


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8.Create a 10x10 array with random values and find the minimum and maximum values.

In [11]:
a=np.random.randint(0,100,(10,10))
print(a.min())
print(a.max())

0
99


9.Create a 3*3 matrix and print it's transpose matrix

In [12]:
a = np.arange(0,9)
b = a.reshape(3,3)
print(b)
print("\n")
c = b.transpose()
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[0 3 6]
 [1 4 7]
 [2 5 8]]


10.Create two arrays of 2-D and find dot product of it.

In [14]:
a=np.random.randint(1,10,(2,2))
b=np.random.randint(1,10,(2,2))
print(a)
print(b)
print(a.dot(b))

[[1 9]
 [9 2]]
[[5 5]
 [7 2]]
[[68 23]
 [59 49]]


11.Compute the maximum for each row in the given array.

In [15]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print("Matrix = \n",a)
np.max(a,1)

Matrix = 
 [[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]


array([9, 8, 6, 3, 9])

12.Select 3rd & 5th row and 3rd & 4th columns## 

In [16]:
data = np.random.randint(10,100,(5,4))
print(data)
data[[2,4],2:4]

[[25 70 68 26]
 [19 96 12 37]
 [14 41 11 23]
 [93 14 69 77]
 [17 59 57 75]]


array([[11, 23],
       [57, 75]])

13.Convert below matrix into vector

In [17]:
matrix = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

14.The product of two inverse matrix is identical matrix,prove

In [22]:
m = np.array([[2,3],
              [2,4]])
print(m)
n=np.linalg.inv(m)
print(n)
print(n.dot(m))

[[2 3]
 [2 4]]
[[ 2.  -1.5]
 [-1.   1. ]]
[[1. 0.]
 [0. 1.]]


15.Create a matrix from a uniform distribution over [0, 1)

In [23]:
a = np.random.uniform(1,0,5)
print(a)

[0.70112365 0.43125447 0.82137568 0.4674263  0.35330853]
